-- REST_INFO 테이블에서 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM 
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE) AS X
INNER JOIN REST_INFO AS I ON I.FOOD_TYPE = X.FOOD_TYPE AND I.FAVORITES = X.FAVORITES
ORDER BY FOOD_TYPE DESC