-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I
RIGHT JOIN ANIMAL_OUTS O USING (ANIMAL_ID)
ORDER BY (O.DATETIME - I.DATETIME) DESC
LIMIT 2

# 보호 기간 ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME