-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (SUM(AMOUNT) * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P
INNER JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID AND PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC