-- 자동차 종류가 '세단'인 자동차들 중 10월에 대여를 시작한 기록이 있는 자동차 ID 리스트
SELECT DISTINCT(CAR_ID) AS CAR_ID
FROM 
    CAR_RENTAL_COMPANY_CAR C
INNER JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H USING (CAR_ID)
WHERE 
    C.CAR_TYPE = '세단'
AND
    DATE_FORMAT(START_DATE, '%Y-%m') = '2022-10' 
ORDER BY
    CAR_ID DESC

